### ISSUE TITLE
Growth curve analysis by FCM

### ISSUE THREAD

**Issue by rprops** [rprops/Phenoflow_package#1]
Direct analysis of growth curves from FCM data.

**Comment by FMKerckhof** [comment]
do you mean here by processing a batch of FCS files in a single directory and using their time-stamp metadata, or how would you like to proceed?

**Comment by rprops** [comment]
Yeah - input would be FCS files and a file linking FCS file to timepoint.  Analysis would be data import -> gating -> extract counts -> growth curve analysis.

**Comment by FMKerckhof** [comment]
I have test data available, let me know if you'd like to take a stab at it: https://github.ugent.be/RamanCluster/GrowthCurveDecember

**Comment by rprops** [comment]
I have code available for this, as I've done this on online FCM data
