### ISSUE TITLE
Adding non-CRAN packages

### ISSUE THREAD

**Issue by rprops** [rprops/Phenoflow_package#11]
Have to look into how to automatically install non-CRAN packages (flowCore, flowViz, easyGgplot2)

**Comment by FMKerckhof** [comment]
https://www.biostars.org/p/178056/

**Comment by FMKerckhof** [comment]
It is possible that we need to make this a bioconductor package...

**Comment by rprops** [comment]
There are currently issues with devtools and remote repositories. Can't include remote repositories or get the following error in all build attempts: "Error in curl::curl_fetch_disk(url, x$path, handle = handle) : URL using bad/illegal format or missing URL"

**Comment by FMKerckhof** [comment]
Should we maybe add it as an issue to hadley/devtools? https://github.com/hadley/devtools/issues

**Comment by rprops** [comment]
Its already an open issue: https://github.com/hadley/devtools/issues/1381

**Comment by rprops** [comment]
There is a workaround by putting these packages in suggests and installing them when the function is first called: http://r-pkgs.had.co.nz/description.html

**Comment by rprops** [comment]
Closing for now.
