### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#12]
http://r-pkgs.had.co.nz/package.html : see name criteria

**Comment by FMKerckhof** [comment]
no _ allowed in package names

**Comment by rprops** [comment]
Package name in DESCRIPTION file is "Phenoflow". Just github repo is named differently to not conflict with the existing phenoflow repo. Does still pose an issue?

**Comment by FMKerckhof** [comment]
No, as you can see from the travis CI results in the release version R CMD check does not give any problems
