### ISSUE TITLE
Issue with masking

### ISSUE THREAD

**Issue by rprops** [rprops/Phenoflow_package#16]
Phyloseq is masking some functions from other packages (even though these functions are never used) resulting in a failed Travis build...

![image](https://cloud.githubusercontent.com/assets/19682548/20651135/1e35630e-b4ad-11e6-95f3-1e5d315f9db2.png)

**Comment by FMKerckhof** [comment]
Normally warnings shouldn't trow a travis error... I'll investigate

**Comment by rprops** [comment]
I fixed it - added extra line to travis.yml
