### ISSUE TITLE
Incorporate inext functions Diversity_16S()

### ISSUE THREAD

**Issue by rprops** [rprops/Phenoflow_package#20]

**Comment by FMKerckhof** [comment]
https://cran.r-project.org/web/packages/iNEXT/index.html

**Comment by rprops** [comment]
Major issue on current test implementation: incredibly slow for microbial community data. That is, its taking > 5 days to run on a data set of 500 samples / 80,000 OTUs..

**Comment by FMKerckhof** [comment]
We could take a dive in the code and see what is keeping it behind, I'll put it on the backburner for now.

**Comment by rprops** [comment]
Extra test by colleague, after 10 days running didn't finish. Doesn't seem designed for seq data..

**Comment by FMKerckhof** [comment]
The current implementation of diversity indices with bootstrapping in the Phenoflow package would not be improved by using iNext functions. It also appears that there is no ongoing development (almost a nine months no commits to master at https://github.com/JohnsonHsieh/iNEXT). Therefore we consider this issue closed.
