### ISSUE TITLE
Leinster & Cobbold implementation

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#27]
A similarity-sensitive diversity metric may be of added value. Phyloseq's data structure allows including a phylogenetic tree within the object, which should be relatively eassy to extract distance information from. However, the question remains: how would you make a similarity-sensitive metric on flowcytometric fingerprint data?

**Comment by FMKerckhof** [comment]
Alternatively, we could let the user provide any distance matrix of their choice to Diversity_16S

**Comment by rprops** [comment]
Would need to check formula for calculating the similarity based diversity metrics but should be fairly straightforward to implement, I think

**Comment by rprops** [comment]
Started working on it.

**Comment by FMKerckhof** [comment]
I wouldn't mind doing this in lieu of you, but I am only available from the 2nd of Feb on.

**Comment by rprops** [comment]
Sure you can go for it - I'm curious. I'm afraid the computation of those indices will take a lot of time, due to the size of the expected dissimilarity matrix.

**Comment by FMKerckhof** [comment]
would there be a heuristic approach?

**Comment by FMKerckhof** [comment]
@rprops what about using the Mahalanobis distance? Or is it too sensitive to the number of selected parameters?

**Comment by rprops** [comment]
Not possible (for now) to include in Phenoflow given the type of data we get from FCM.
