### ISSUE TITLE
add flowclean for QC in default pipeline (on wiki?)

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#29]
Recently, we saw with the Accuri that in high-throuphut experiments there could occur missed issues on stability of the data. Could we implement a standardized check? We already (briefly) evaluated flowClean (http://bioconductor.org/packages/release/bioc/html/flowClean.html), however it appears to be quite slow.

Suggestions:
 - We develop our own autocorrelation-based approach
 - We optimize the flowClean code and include it here

**Comment by rprops** [comment]
It is unclear to me how flowClean adjusts the volume measured based on the events removed? Removing spurious and erroneous measurements is a good thing for the diversity assessment but will bias the counts. I'll try to evaluate it on the test data set and try to incorporate it into the `Diversity_rf` and `beta_div_fcm` functions as an additional option.

**Comment by FMKerckhof** [comment]
if you'd need to evaluate/validate it with test data, say a defined concentration of peak beads, I could create the required FCS files with the FACSVerse or the C6

**Comment by rprops** [comment]
I've implemented the `flowClean` function in the `Diversity_rf` function and tested in on the test data (`flowData`) but it did not detect any outliers. Will update wiki.

**Comment by rprops** [comment]
Wiki is updated for alpha div. Will update beta div function to offer the same functionality.

**Comment by rprops** [comment]
Have adjusted wiki - so everything should be good to go.

**Comment by FMKerckhof** [comment]
However, for sure with the latest release, the flowAI bioconductor package is probably the better option.
