### ISSUE TITLE
Add fcs to csv export of flowdata_transformed_all for downstream machine learning

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#30]
A simple R alternative to python fcsparser:parse (https://github.com/eyurtsev/fcsparser/blob/master/fcsparser/api.py) should be able to do the trick.

**Comment by FMKerckhof** [comment]
This should be fairly straightforward: the data frame is contained within the script already and only needs to be stored separately.

**Comment by rprops** [comment]
Will close since we are aiming to pool everything in Phenoflow (incl ML)
