### ISSUE TITLE
Implement Random forrest in R

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#31]
This should be fairly straightforward by translating prubbens python code (https://github.com/prubbens/InSilicoFlow/blob/master/insilico.py)
to R with: https://cran.r-project.org/web/packages/randomForest/index.html and https://cran.r-project.org/web/packages/party/index.html

**Comment by prubbens** [comment]
Might not be a bad idea to look at the state-of-the art. See for example: https://arxiv.org/abs/1508.04409. 
(I am not so familiar with R, but I know that the machine learning modules are much more scattered than in for example Python).

**Comment by rprops** [comment]
Most ML methods are available in the comprehensive caret package: http://topepo.github.io/caret/available-models.html

**Comment by prubbens** [comment]
Didn't know that (still an R-beginner), looks good.

**Comment by prubbens** [comment]
This package seems quite promising: https://github.com/mlr-org/mlr

**Comment by rprops** [comment]
Implemented `caret` Random Forest implementation. Will evaluate in the near future if we shift to mlr.
