### ISSUE TITLE
Error in the wiki: some alpha-diversity components are not calculated

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#41]
In the wiki, at one point,

```R
### Export ecological data to .csv file in the chosen directory
write.csv2(file="results.metrics.csv",
           cbind(Diversity.fbasis, Evenness.fbasis,
                                          Structural.organization.fbasis,
                 Coef.var.fbasis))
```

is called. 

However, currently the objects `Evenness.fbasis`,  `Structural.organization.fbasis`,  `Coef.var.fbasis` are not generated in the alpha-diversity section. 
In the corresponding vignette, I will remove them from this chunck. However @rprops : how would you like to proceed here? Shall we keep them in the wiki? Should they be added to the vignette?

**Comment by rprops** [comment]
Removed those functions from the wiki. They haven't been properly validated/tested.

**Comment by FMKerckhof** [comment]
I'll add to the vignette that also the results of the diversity_rf get exported:

```R
### Export ecological data to .csv file in the chosen directory
names(Diversity.clean) <- paste0(names(Diversity.clean),".clean")
write.csv2(file="results.metrics.csv",
           cbind(Diversity.fbasis,Diversity.clean))
```
