### ISSUE TITLE
Columns in confusion matrix after RandomForest training seem to be swapped around

### ISSUE THREAD

**Issue by prubbens** [rprops/Phenoflow_package#51]
This makes interpretation counter-intuitive, as the goal for most classification purposes is to achieve a diagonal matrix.

**Comment by rprops** [comment]
Ok wil adress next window I have.

**Comment by FMKerckhof** [comment]
any update on this matter?

**Comment by rprops** [comment]
The confusion matrix isn't wrong, it's just a mirrored version of what "most people" are used to. I will address soon.
