### ISSUE TITLE
Shouldn't -W be included in the case of FACSVerse data in the build up to filter params for flowAI::autoQC?

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#58]
See e.g.

https://github.com/rprops/Phenoflow_package/blob/00687dccccd192a0fa40969f205b68b2d2de46f6/R/RandomF_predict.R#L44

**Comment by rprops** [comment]
Will come down to the same thing in 99% of the cases as you won't feed a -W parameter w/o the -A/-H included. But will adjust in next commit so it can handle that.

**Comment by FMKerckhof** [comment]
No worries, I'll make a PR, since it is relevant to me

**Comment by FMKerckhof** [comment]
Fixed in 53a639374d8d780b9d249e62b19b3a425b4bf255
