### ISSUE TITLE
RandomF_FCS error

### ISSUE THREAD

**Issue by rprops** [rprops/Phenoflow_package#64]
![fig](https://user-images.githubusercontent.com/19682548/56648149-11fc3100-6683-11e9-89b9-19238cc15574.png)

**Comment by FMKerckhof** [comment]
experiencing similar errors with diversity_rf

**Comment by rprops** [comment]
does this occur on flowAI denoised data or on normal data too?

**Comment by FMKerckhof** [comment]
in my case it occured on normal (i.e. transformed, but not cleaned) data too, I looked at `Diversity_rf`and it happens when applying `x <- x[, param]`

**Comment by FMKerckhof** [comment]
specifically, this type of subsetting appears to break after running `mytrans` in `flowCore::transform`

**Comment by FMKerckhof** [comment]
I have pinpointed the issue (at least in my dataset). Right before the `mytrans`  normalization, we use `flowCore::Subset` to separate the cellular fraction. It would appear that, at least in my case, some samples retained 0 cells. This makes the transformation return a non-numeric matrix (i.e. a null matrix), which returns the error. Diagnostic: `which(unlist(fsApply(flowData_transformed,function(x)is.numeric(x@exprs)))==FALSE)` if this returns anything else but `named integer (0)` there are samples that are problematic. Even with 1 cell, it will still work, therefore I am now applying an additional subsetting step to assure that there are at least 500 cells in the sample.
