### ISSUE TITLE
Installation issue: ERROR: dependency ‘flowFDA’ is not available for package ‘Phenoflow’

### ISSUE THREAD

**Issue by vetrabindra01** [rprops/Phenoflow_package#72]
I am having installation issues. Please let me know. Below are errors and session_info.

> install_github("CMET-UGent/Phenoflow_package")
Downloading GitHub repo CMET-UGent/Phenoflow_package@HEAD
Downloading GitHub repo FMKerckhof/flowFDA@HEAD
✔  checking for file ‘/private/var/folders/64/58fk04bx2335w895j8x608080000gn/T/RtmpvxRbct/remotes6637b127045/FMKerckhof-flowFDA-b6d8ec6/DESCRIPTION’ ...
─  preparing ‘flowFDA’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘flowFDA_0.99.tar.gz’
   
* installing *source* package ‘flowFDA’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in if (class(mclustProt[[i]]) == "try-error") { : 
  the condition has length > 1
Error: unable to load R code in package ‘flowFDA’
Execution halted
ERROR: lazy loading failed for package ‘flowFDA’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/flowFDA’
Downloading GitHub repo FMKerckhof/flowFDA@HEAD
Skipping flowFDA, it is already being installed
✔  checking for file ‘/private/var/folders/64/58fk04bx2335w895j8x608080000gn/T/RtmpvxRbct/remotes663b2c949e/CMET-UGent-Phenoflow_package-e8d096b/DESCRIPTION’ ...
─  preparing ‘Phenoflow’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Phenoflow_1.1.2.tar.gz’
   
ERROR: dependency ‘flowFDA’ is not available for package ‘Phenoflow’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Phenoflow’
Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/64/58fk04bx2335w895j8x608080000gn/T//RtmpvxRbct/file66377890122/flowFDA_0.99.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/64/58fk04bx2335w895j8x608080000gn/T//RtmpvxRbct/file6635b5001f0/Phenoflow_1.1.2.tar.gz’ had non-zero exit status

> session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       macOS Big Sur 11.5.2
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Indiana/Indianapolis
 date     2022-06-02
 rstudio  2022.02.2+485 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package            * version date (UTC) lib source
 Biobase            * 2.56.0  2022-04-26 [1] Bioconductor
 BiocGenerics       * 0.42.0  2022-04-26 [1] Bioconductor
 BiocManager        * 1.30.18 2022-05-18 [1] CRAN (R 4.2.0)
 brio                 1.1.3   2021-11-30 [1] CRAN (R 4.2.0)
 cachem               1.0.6   2021-08-19 [1] CRAN (R 4.2.0)
 callr                3.7.0   2021-04-20 [1] CRAN (R 4.2.0)
 cli                  3.3.0   2022-04-25 [1] CRAN (R 4.2.0)
 codetools            0.2-18  2020-11-04 [1] CRAN (R 4.2.0)
 crayon               1.5.1   2022-03-26 [1] CRAN (R 4.2.0)
 curl                 4.3.2   2021-06-23 [1] CRAN (R 4.2.0)
 cytolib              2.8.0   2022-04-26 [1] Bioconductor
 desc                 1.4.1   2022-03-06 [1] CRAN (R 4.2.0)
 devtools           * 2.4.3   2021-11-30 [1] CRAN (R 4.2.0)
 ellipsis             0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
 fastmap              1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
 flowCore           * 2.8.0   2022-04-26 [1] Bioconductor
 flowFDAExampleData * 0.99    2022-06-01 [1] Github (lievenclement/flowFDAExampleData@e187edf)
 flowFP             * 1.54.0  2022-04-26 [1] Bioconductor
 flowViz            * 1.60.0  2022-04-26 [1] Bioconductor
 fs                   1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
 glue                 1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
 hexbin               1.28.2  2021-01-08 [1] CRAN (R 4.2.0)
 IDPmisc              1.1.20  2020-01-21 [1] CRAN (R 4.2.0)
 jpeg                 0.1-9   2021-07-24 [1] CRAN (R 4.2.0)
 KernSmooth           2.23-20 2021-05-03 [1] CRAN (R 4.2.0)
 lattice            * 0.20-45 2021-09-22 [1] CRAN (R 4.2.0)
 latticeExtra         0.6-29  2019-12-19 [1] CRAN (R 4.2.0)
 lifecycle            1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
 magrittr             2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
 MASS               * 7.3-57  2022-04-22 [1] CRAN (R 4.2.0)
 Matrix               1.4-1   2022-03-23 [1] CRAN (R 4.2.0)
 matrixStats          0.62.0  2022-04-19 [1] CRAN (R 4.2.0)
 mclust             * 5.4.10  2022-05-20 [1] CRAN (R 4.2.0)
 memoise              2.0.1   2021-11-26 [1] CRAN (R 4.2.0)
 multcomp           * 1.4-19  2022-04-26 [1] CRAN (R 4.2.0)
 mvtnorm            * 1.1-3   2021-10-08 [1] CRAN (R 4.2.0)
 pkgbuild             1.3.1   2021-12-20 [1] CRAN (R 4.2.0)
 pkgload              1.2.4   2021-11-30 [1] CRAN (R 4.2.0)
 png                  0.1-7   2013-12-03 [1] CRAN (R 4.2.0)
 prettyunits          1.1.1   2020-01-24 [1] CRAN (R 4.2.0)
 processx             3.5.3   2022-03-25 [1] CRAN (R 4.2.0)
 ps                   1.7.0   2022-04-23 [1] CRAN (R 4.2.0)
 purrr                0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
 R6                   2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
 RColorBrewer         1.1-3   2022-04-03 [1] CRAN (R 4.2.0)
 Rcpp                 1.0.8.3 2022-03-17 [1] CRAN (R 4.2.0)
 RcppParallel         5.1.5   2022-01-05 [1] CRAN (R 4.2.0)
 remotes              2.4.2   2021-11-30 [1] CRAN (R 4.2.0)
 rlang                1.0.2   2022-03-04 [1] CRAN (R 4.2.0)
 rprojroot            2.0.3   2022-04-02 [1] CRAN (R 4.2.0)
 RProtoBufLib         2.8.0   2022-04-26 [1] Bioconductor
 rstudioapi           0.13    2020-11-12 [1] CRAN (R 4.2.0)
 S4Vectors            0.34.0  2022-04-26 [1] Bioconductor
 sandwich             3.0-1   2021-05-18 [1] CRAN (R 4.2.0)
 sessioninfo          1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
 survival           * 3.3-1   2022-03-03 [1] CRAN (R 4.2.0)
 testthat             3.1.4   2022-04-26 [1] CRAN (R 4.2.0)
 TH.data            * 1.1-1   2022-04-26 [1] CRAN (R 4.2.0)
 usethis            * 2.1.6   2022-05-25 [1] CRAN (R 4.2.0)
 withr                2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
 zoo                  1.8-10  2022-04-15 [1] CRAN (R 4.2.0)

 [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library

Sincerely,
Rabindra

**Comment by FMKerckhof** [comment]
should be resolved in FMKerckhof/flowFDA@a7e931d
