### ISSUE TITLE
maybe add travis ci  build checks?

### ISSUE THREAD

**Issue by FMKerckhof** [rprops/Phenoflow_package#8]
So that users have confidence that devtools::install_github() will deliver 
https://docs.travis-ci.com/user/languages/r/

**Comment by FMKerckhof** [comment]
first yml added in 7f9ba99d1df319030d1205baf4a847d841dc856e

**Comment by FMKerckhof** [comment]
@rprops : as repo owner you should add repo to travis ci: https://docs.travis-ci.com/user/getting-started/

**Comment by rprops** [comment]
Done!

**Comment by FMKerckhof** [comment]
https://travis-ci.org/rprops/Phenoflow_package/jobs/175374929
